/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 /Users/zenneson/Desktop/Cre8ive 4mula/cre8ive4mula/public/model/spiral.glb 
*/

import { PerspectiveCamera, useAnimations, useGLTF } from "@react-three/drei";
import { useRef } from "react";

export function Spiral(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/model/spiral.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="__root__">
          <mesh
            name="0053"
            geometry={nodes["0053"].geometry}
            material={materials.Black}
            position={[-0.031, -0.032, -2.03]}
            scale={0.509}
          />
        </group>
        <group name="IS-hemispheric-light" />
        <PerspectiveCamera
          name="IS-camera"
          makeDefault={false}
          far={10000}
          near={1}
          fov={45.837}
          position={[-7.926, 2, -1.089]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model/spiral.glb");
