/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 /Users/zenneson/Desktop/Cre8ive 4mula/cre8ive4mula/public/model/wireBall.glb 
*/

import { PerspectiveCamera, useGLTF } from "@react-three/drei";

export function WireBall(props) {
  const { nodes, materials } = useGLTF("/model/wireBall.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={10000}
        near={1}
        fov={45.837}
        position={[-6.693, 2, 4.382]}
      />

      <mesh
        geometry={nodes.Icosphere.geometry}
        material={materials["Material.008"]}
        rotation={[0.441, 0, 0]}
        scale={0.697}
      >
        <meshStandardMaterial
          attach="material"
          metalness={1}
          roughness={0}
          envMapIntensity={1}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/model/wireBall.glb");
